version: 2.0
jobs:
 build:
   machine:
     enabled: true
     image:   circleci/classic:Latest
   steps:
     - run:
         name: Update npm
         command: |
                  npm install -g npm@latest
     - run:
         name: Install lftp
         command: |
                  sudo apt-get install lftp
           
