version: 2.0
jobs:
  deploy-job:
    machine:
      enabled: true
      image:   circleci/classic:201708-01
    working_directory: ~/
    steps:
	     - run:
        name: Update npm
        command: |
                  npm install -g npm@latest
      - run:
        name: Install lftp
        command: |
                  sudo apt-get update
                  sudo apt-get install lftp
#      - checkout
