version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: Update npm
         command: |
                  sudo npm install -g npm@latest
     - run:
         name: Install lftp
         command: |
                  install -g lftp
           
